# Github Actions 작성 가이드 : https://docs.github.com/actions
# Node 작성 가이드 : https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
# Nexus 작성 가이드 : https://github.com/marketplace/actions/nexus-repository-publisher-for-github-actions

# NPM 기본 registry 경로 = https://registry.npmjs.org/
# -> 외부 라이브러리 참조 시 사용한다. (Vue, Vite...)
# 사설 registry 경로 = https://nexus.ajdlabs.kr/repository/npm-private/
# -> fronkk 컴포넌트의 변경사항 참조 혹은 외부에서의 참조 시 사용한다

### 웹훅 시나리오
# 1. local에서 변경사항 발생 & remote 브랜치 업데이트
# 2. remote develop - 병합
# 3. remote main - 병합 - 여기까지는 작업자가 반영해야 한다
# 4. remote main - 빌드 ** 여기부터 yml 스크립트로 실행된다
# 5. remote main - 배포

name: Automate Build and Publish

on:
  pull_request:
    branches: [ 'develop' ] # TODO , 'main'으로 수정 필요

jobs:
  build: # 임의로 작성한 id, 변경 가능 (프로젝트 고유 변수명처럼 사용)
    runs-on: ubuntu-latest # 프로세스를 실행할 환경
    steps: # 실행될 스크립트
      - uses: actions/checkout@v3
      - run: npm install --registry https://registry.npmjs.org/ # package-lock.json에 명시된 패키지를 node_modules에 적재
      - run: npm run build
      - run: npm publish --registry https://nexus.ajdlabs.kr/repository/npm-private/:_authToken="admin:aj@dev"
      - uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://nexus.ajdlabs.kr
          username: admin
          password: aj@dev
          format: maven2
          repository: npm-private
          coordinates: groupId=com.example artifactId=app version=1.0.0
          assets: extension=jar
          filename: ./fronkk-0.0.4.jar
