name: Package to Nexus Repository

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build with Maven
        run: mvn package --file pom.xml
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with: 
          serverUrl: https://nexus.ajdlabs.kr
          username: admin
          password: aj@dev
          format: maven2
          repository: npm-private
          coordinates: groupId=com.example artifactId=app version=0.0.3
          assets: extension=jar
          filename: ./target/app-1.0.0.jar
